# Generated by Django 3.0.7 on 2021-06-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(default='', verbose_name='Content')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('preview', models.CharField(default='', max_length=5000)),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.IntegerField(default=5, help_text='in minutes', verbose_name='Read Time')),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('Featured', 'Featured'), ('Recent', 'Recent'), ('Popular', 'Popular'), ('Quantum-Mechanics', 'Quantum-Mechanics'), ('Nuclear-Physics', 'Nuclear-Physics'), ('Optics', 'Optics'), ('Fluids', 'Fluids'), ('Classical-Mechanics', 'Classical-Mechanics'), ('Calculus', 'Calculus'), ('Linear-Algebra', 'Linear-Algebra'), ('Special-Relativity', 'Special-Relativity'), ('Electrodynamics', 'Electrodynamics'), ('Astronomy', 'Astronomy')], default='Featured', max_length=100)),
                ('featured_image', models.ImageField(default='default.png', upload_to='blog_pics', verbose_name='Featured Image')),
                ('note', models.FileField(blank=True, default=None, null=True, upload_to='notes', verbose_name='Notes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
            ],
        ),
    ]
