# Generated by Django 4.1.7 on 2023-09-29 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default=None, max_length=100)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.contentcat')),
            ],
        ),
        migrations.CreateModel(
            name='RSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('summary', models.CharField(default=None, max_length=5000)),
                ('content', models.TextField(default=None, verbose_name='Content')),
                ('story_link', models.CharField(default=None, max_length=5000)),
                ('media_link', models.CharField(default=None, max_length=5000)),
                ('date_posted', models.DateTimeField(default=None)),
                ('tag', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('preview', models.CharField(default=None, max_length=5000)),
                ('content', models.TextField(default=None, verbose_name='Content')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.IntegerField(default=5, help_text='in minutes', verbose_name='Read Time')),
                ('featured_image', models.ImageField(default='default.png', upload_to='blog_pics', verbose_name='Featured Image')),
                ('note', models.FileField(blank=True, default=None, help_text='(Optional)', null=True, upload_to='notes', verbose_name='Notes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=100, verbose_name='Name')),
                ('comment', models.TextField(default=None, verbose_name='Comment')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
