# Generated by Django 4.1.7 on 2023-09-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(default=None, null=True, to='blog.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ManyToManyField(default=None, null=True, to='blog.contentcat'),
        ),
    ]
