# Generated by Django 3.0.7 on 2020-12-26 14:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='note',
            field=models.FileField(blank=True, default=None, null=True, upload_to='notes', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Featured', 'Featured'), ('Recent', 'Recent'), ('Popular', 'Popular'), ('Quantum-Mechanics', 'Quantum-Mechanics'), ('Nuclear-Physics', 'Nuclear-Physics'), ('Optics', 'Optics'), ('Fluids', 'Fluids'), ('Classical-Mechanics', 'Classical-Mechanics'), ('Calculus', 'Calculus'), ('Linear-Algebra', 'Linear-Algebra'), ('Special-Relativity', 'Special-Relativity'), ('Electrodynamics', 'Electrodynamics'), ('Astronomy', 'Astronomy')], default='Featured', max_length=100),
        ),
    ]
