# Generated by Django 4.1.7 on 2023-09-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_tag_remove_tag_category_post_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rss',
            name='tag',
        ),
        migrations.AddField(
            model_name='rss',
            name='tag',
            field=models.ManyToManyField(default=None, null=True, to='blog.tag'),
        ),
    ]
