# Generated by Django 4.1.7 on 2023-09-26 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_alter_post_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('summary', models.CharField(default='', max_length=5000)),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('story_link', models.CharField(default='', max_length=5000)),
                ('media_link', models.CharField(default='', max_length=5000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
