# Generated by Django 4.1.7 on 2023-09-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rsspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
