# Generated by Django 4.1.7 on 2023-09-27 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_rsspost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsspost',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
