# Generated by Django 4.1.7 on 2023-09-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_rsspost_date_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSSPost',
        ),
    ]
