# Generated by Django 4.1.7 on 2023-09-27 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_rsspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='RSSPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('summary', models.CharField(default='', max_length=5000)),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('story_link', models.CharField(default='', max_length=5000)),
                ('media_link', models.CharField(default='', max_length=5000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='blog.tag')),
            ],
        ),
    ]
