# Generated by Django 4.1.7 on 2023-09-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_category_category_name_alter_tag_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsspost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.tag'),
        ),
    ]
