# Generated by Django 4.1.7 on 2023-09-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_rsspost_rss_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsspost',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.tag'),
            preserve_default=False,
        ),
    ]
