# Generated by Django 4.1.7 on 2023-09-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rsspost_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RSSPost',
            new_name='RSS',
        ),
    ]
