# Generated by Django 4.1.7 on 2023-09-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_tag_alter_rss_tag_alter_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.contentcat'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
