# Generated by Django 4.1.7 on 2023-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_contentcat_alter_tag_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcat',
            name='category_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='rss',
            name='media_link',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='rss',
            name='story_link',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='rss',
            name='summary',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='rss',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
