# Generated by Django 4.1.7 on 2023-09-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_contentcat_category_name_alter_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rss',
            name='tag',
        ),
    ]
