# Generated by Django 4.1.7 on 2023-09-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.DeleteModel(
            name='ContentCat',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
