TAG_OPTIONS = (
    ("Featured","Featured"),
    ("Recent","Recent"),
    ("Popular","Popular"),
    ("Quantum-Mechanics","Quantum-Mechanics"),
    ("Nuclear-Physics","Nuclear-Physics"),
    ("Optics","Optics"),
    ("Fluids","Fluids"),
    ("Classical-Mechanics","Classical-Mechanics"),
    ("Calculus","Calculus"),
    ("Linear-Algebra","Linear-Algebra"),
    ("Special-Relativity","Special-Relativity"),
    ("Electrodynamics","Electrodynamics"),
    ("Astronomy","Astronomy"),
)